/**
 * Display names for Instant Virtual matches.
 * Labels only — outcomes are pure server RNG, not linked to real results.
 */
export const VIRTUAL_TEAM_POOL: string[] = [
  // Premier League style
  "Arsenal",
  "Chelsea",
  "Liverpool",
  "Manchester City",
  "Manchester United",
  "Tottenham",
  "Newcastle",
  "Aston Villa",
  "Brighton",
  "West Ham",
  "Fulham",
  "Crystal Palace",
  "Brentford",
  "Wolves",
  "Everton",
  "Nottingham Forest",
  // La Liga
  "Real Madrid",
  "Barcelona",
  "Atletico Madrid",
  "Sevilla",
  "Real Sociedad",
  "Villarreal",
  "Athletic Bilbao",
  "Real Betis",
  // Serie A
  "Inter",
  "AC Milan",
  "Juventus",
  "Napoli",
  "Roma",
  "Lazio",
  "Atalanta",
  "Fiorentina",
  // Bundesliga
  "Bayern Munich",
  "Borussia Dortmund",
  "RB Leipzig",
  "Bayer Leverkusen",
  "Eintracht Frankfurt",
  "Wolfsburg",
  // Ligue 1
  "PSG",
  "Marseille",
  "Monaco",
  "Lyon",
  "Lille",
  "Nice",
  // Others
  "Ajax",
  "PSV",
  "Benfica",
  "Porto",
  "Sporting CP",
  "Celtic",
  "Rangers",
  "Galatasaray",
  "Fenerbahce",
  "Al Hilal",
  "Al Nassr",
  "Inter Miami",
  "LA Galaxy",
  "Flamengo",
  "Palmeiras",
  "River Plate",
  "Boca Juniors",
];
